---

- name: Remove NOPASSWD for user in sudoer file
  sudo: yes
  lineinfile:
    backup: yes
    dest: /etc/sudoers
    state: absent
    regexp: '^{{ sudo_nopasswd_user }} ALL=\(ALL\) NOPASSWD: ALL$'
    validate: 'visudo -cf %s'
  register: sudoers

- debug:
    msg: "Location of sudoers backup file: {{ sudoers.backup }}"
