---

- name: Download Packer
  get_url: 
    url: https://dl.bintray.com/mitchellh/packer/packer_0.8.3_linux_amd64.zip
    dest: '{{ temp_work_area }}/packer.zip'

- name: Install Packer
  unarchive:
    src: '{{ temp_work_area }}/packer.zip'
    dest: /usr/local/bin
    copy: no