---

- name: Set User Preferences
  osx_defaults:
    domain: '{{ item.0.domain }}'
    key: '{{ item.1.key }}'
    type: '{{ item.1.type }}'
    value: '{{ item.1.value }}'
    state: present
  with_subelements:
    - osx_defaults
    - defaults

- name: Relaunch Dock
  command: killall Dock

- name: Relaunch Finder
  command: killall Finder
