---
galaxy_info:
  author: sundeer
  description: Ansible role for provisioning rs-dev
  license: MIT
  min_ansible_version: 1.2
  platforms:

  - name: Ubuntu
    versions:
       - vivid
dependencies:
#  - dirn.homebrew
